### ISSUE TITLE
Why is this package needed?

### ISSUE THREAD

**Issue by martint17r** [joonix/log#2]
I am not sure how your code makes a difference against using the standard JSONFormatter like this:
```golang
logrus.SetFormatter(&log.JSONFormatter{
    FieldMap: logrus.FieldMap{
        logrus.FieldKeyTime:  "time",
        logrus.FieldKeyLevel: "severity",
        logrus.FieldKeyMsg:   "message",
    },
})
```
Could you please elaborate?

**Comment by balboah** [comment]
I was not aware of the FieldMap option, it's probably enough to use that. Thank you for providing an example

**Comment by MrWako** [comment]
... just to add that it also maps the logrus severity levels to the fluentd severity levels.
