### ISSUE TITLE
Not parsing correctly

### ISSUE THREAD

**Issue by johan-lejdung** [joonix/log#7]
Hi!

I am using you package but it is still not parsing correctly. I end up getting a json string in my textPayload field.

I suspect I have something weird going on in the fluentd configmap. Do you have an example that works?

**Comment by balboah** [comment]
The configuration I've used it for is the default that runs on google cloud kubernetes. I have no fluentd configmap and I have not deployed fluentd by myself. The full example is already provided in the README.md.

You can easily run the example code by copying it to a main.go and build with Dockerfile:
```
FROM golang:alpine

RUN apk --update add git
RUN go get github.com/joonix/log
RUN go get github.com/sirupsen/logrus
COPY main.go /main.go

ENTRYPOINT ["go", "run", "/main.go"]
```

**Comment by johan-lejdung** [comment]
For others that might be having the same issue. I had very stupidly installed another fluentd daemonset ONTOP of the default installed one "hidden" under the namespace `kube-system`.

You can view it with `kubectl daemonset --namespace=kube-system`.
After removing the one I installed and restarting that one (`kubectl delete pod <POD> --namespace=kube-system`) it started working :)
